Add spotless/ktlint gradle plugin
afterpay/sdk-android pull request #225
Opened 2024-07-03 21:26 UTC by tir38

I'll tie `spotlessCheck` to github actions once it's merged in.

2024-07-03 22:15 UTC, ScottAntonacAP approved these changes

2024-07-04 13:24 UTC, mmroz approved these changes

2024-07-04 15:33 UTC, pedronveloso requested changes
Nice. Would love to see a follow-up PR that adds enforcement via GitHub Actions - so that it would for this on every new PR. Made a comment regarding LICENSE header

2024-07-04 15:33 UTC, pedronveloso commented on build.gradle.kts
> +            licenseHeader("// Copyright Block, Inc.")
I think this is actually in conflict with the actual license in the project. It currently uses APACHE ( https://github.com/afterpay/sdk-android/blob/master/LICENSE).
I recall going trough this with J Wilson, here's an example of what it should probably look like: https://github.com/cashapp/cash-app-pay-android-sdk/blob/main/build.gradle#L47

might need to tweak the entity, but you get the gist

2024-07-12 17:43 UTC, merged